### ISSUE TITLE
Add "Town at %location%" and "Town of %player%" for Towny Support 

### ISSUE THREAD

**Issue by MonoLime** [Sharpjaws/SharpSK#11]
Umbaska dropped the support of Towny expressions such as "Town at %Location%" and "Town of %player%" which returned the String of the Town the player is standing on and the String of the Town the player belongs to. 

Seeing as recent updates have included Towny with this addon. I was wondering if you could pick this expression up?

**Comment by Sharpjaws** [comment]
It has already been planned so this will definitely be added

**Comment by keenerb** [comment]
This is extremely important to me, some of my old scripts are useless now that I've upgraded my server to a more recent build.  Thanks for looking into it.

**Comment by Portanna** [comment]
As those expressions are already handled by some other addon, I suggest adding a facultative [sharpsk] before the expression syntax
