### ISSUE TITLE
 Error when spawning mythicmobs

### ISSUE THREAD

**Issue by GreatRaceofGithub** [Sharpjaws/SharpSK#12]
There is no hindrance to the operation, but an error appears on the console.

https://pastebin.com/iiWvjKaB

**Comment by Sharpjaws** [comment]
Please don't forget to list your Mythicmobs version so I can debug and see where the problem is faster. @GreatRaceofGithub 

Also the code that you used

**Comment by Sharpjaws** [comment]
Closed in commit 78fd8ac . Can't confirm if it's fixed during lack of info for 12+ days.
