### ISSUE TITLE
Conditions for AuthMeReloaded

### ISSUE THREAD

**Issue by cengiz77** [Sharpjaws/SharpSK#17]
Hello! Could you add some conditions for authme?

Examples:
if player is logged in:

if player is not logged in:

**Comment by Snow-Pyon** [comment]
That's already a condition.

**Comment by Sharpjaws** [comment]
@cengiz77  Its already included. Use these conditions:

```
[authme] %player% is authenticated:
[authme] %player% is not authenticated:
```
They are probably what you're looking for.

**Comment by Snow-Pyon** [comment]
Well, as you added the suggestion label, you should put that as an alias, I've seen this kind of question more than a time and that's because `%player% (is|is(n't| not) logged in` fits more with the condition.
