### ISSUE TITLE
Event: On authme login isn't working on 1.12

### ISSUE THREAD

**Issue by YellowZaki** [Sharpjaws/SharpSK#19]
The tittle describes itself.

**Comment by Snow-Pyon** [comment]
What isn't working exactly? Does it throw an error or something? With what version of Skript? You'll have to be more specific.

**Comment by JRoy** [comment]
Are you sure authme supports 1.12?

**Comment by YellowZaki** [comment]
Skript doesn't recognize that event.

**Comment by Sharpjaws** [comment]
Thanks for the report, unfortunately I need a bit more info on the bug. Could you post your server startup log (should be in logs/latest.log) and your Authmereloaded version? should be considerd enough for me to solve it.

**Comment by Sharpjaws** [comment]
Can't seem to reproduce this. Closed because of lack of info for 12+ days.
