### ISSUE TITLE
NullPointerException in timers

### ISSUE THREAD

**Issue by TrademarkTM** [Sharpjaws/SharpSK#2]
Hey SharpJaws!
I've been trying to use the timers of your addon, but they don't seem to work. Here follows the error:
https://hastebin.com/keketuruse.vbs

**Current code:**
```
command /timer:
	trigger:
		create timer "timer" for 10 seconds
````

**Server version:** 1.11.2
**Skript version:** Bensku's Skript dev25

**Comment by Sharpjaws** [comment]
Thanks for reporting this bug to me. It will be fixed asap. 
Also try adding ¨keep active false¨ to the end of the syntax. It will be a temporary solution to prevent the nullpointerexception.
Example:
`create timer ¨sometimer¨ for 10 seconds keep active false`
