### ISSUE TITLE
FactionsUUID Support

### ISSUE THREAD

**Issue by bertek41** [Sharpjaws/SharpSK#23]
Hey man i love your addon im using for timer feature also i need FactionsUUID skript addon can you add support for this plugin? I tried so many FactionsUUID addon but most of them aren't working or spamming error on console.

**Comment by Sharpjaws** [comment]
Sure, I'll look into it

**Comment by Sharpjaws** [comment]
Closed. Already supported by https://forums.skunity.com/resources/conquer.233/
