### ISSUE TITLE
Schematic using deprecated methods?

### ISSUE THREAD

**Issue by xb0t3r** [Sharpjaws/SharpSK#25]
(FAWE) @CuboidClipboard used by EffPasteSchematic.execute():58 is deprecated.

When using your schematic syntax?

Using latest skript dev30 by bensku and using your latest version of sharpSK

**Comment by Sharpjaws** [comment]
This is in most cases considered normal unless it interrupts your placement of schematics. It just lets you know that its working with an older method that is no longer used (but still there) to place the schems. Does it prevent you from placing schems with the syntax?
