### ISSUE TITLE
Skript is not allowing registerations - logger warning

### ISSUE THREAD

**Issue by Z8MB1E** [Sharpjaws/SharpSK#26]
The logger is displaying a warning detailing that Skript cannot allow registerations. Can this be fixed? #

**Comment by Sharpjaws** [comment]
@Z8MB1E  Hi there, Unfortunately I need more info. Could you give me your skript version. the addons (including sharpsk)/plugins that you use and your server version so that I can take alook at it?

**Comment by Z8MB1E** [comment]
Sure thing!
Skript version is: **2.2-dev29**
Server version is: **Spigot 1.12.1 _(Craftbukkit version git-Spigot-5340a52-e1f296d)_**
Plugin list is as follows:
**CoreProtect, MinecraftMarket, ClaimDonation, WorldEdit, Skript, BuildersUtilities, OpenInv, GroupManager, PlaceholderAPI, PacketListenerAPI, ClearLag, PlugMan, SkQuery, ProtocolLib, WorldGuard, LibsDisguises, NoCheatPlus, NoPlugins, ChopTree3, TrollCommandsPlusPlus, ActionAnnouncer, SimpleAPI, Vault, StaffPlus, GriefPrevention, MyPet, Essentials, SharpSK, LockettePro, EssentialsProtect, CrazyAuctions, EssentialsChat, EssentialsAntiBuild, EssentialsSpawn**

**Comment by Sharpjaws** [comment]
Thanks, much appreciated. I'll check it out

**Comment by Sharpjaws** [comment]
@Z8MB1E  Sadly I can't seem to replicate this bug with the exact same setup that you have. Maybe you are running an old version of sharpsk? If so make sure you download the latest version: https://github.com/Sharpjaws/SharpSK/releases/latest  and also make sure your plugins and spigot are up-to-date. If after all that the problem still presists then could you send me your console startup log? (latest.log inside your logs folder), You can send the file or post a pastebin of the log. Thanks
