### ISSUE TITLE
Mcmmo error

### ISSUE THREAD

**Issue by Portanna** [Sharpjaws/SharpSK#28]
You forgot to also set the "get" event of "[mcmmo] %skilltype% level of %offlineplayer%" syntax to be compatible with offlineplayers.

>   protected Integer[] get(Event e)
>   {
>     return new Integer[] { Integer.valueOf(ExperienceAPI.getLevel((Player)this.p.getSingle(e), ((SkillType)this.s.getSingle(e)).toString())) };
>   }

Stacktrace: https://pastebin.com/raw/7AawUbsE

I built the latest sharpsk ( McMMO: Added Offlineplayer support for most syntaxes.) with the latest mcmmo commit with maven.

**Comment by Sharpjaws** [comment]
Thanks, should be fixed with my next commit
