### ISSUE TITLE
WorldEdit Paste Schematic

### ISSUE THREAD

**Issue by Andireas1803** [Sharpjaws/SharpSK#29]
It won't paste a schematic in:
https://pastebin.com/T2xrV3zG

`sharpsk paste schematic "PLANET_LVL_%{temp_::marsland::%{_player_uuid}%::island::level}%" at {temp_::marsland::%{_player_uuid}%::island} exclude air true`
Both of the variables are set.

Server version: Paper 1.12.1-R0.1
Skript version: 2.2-dev31b
SharpSK version: 1.6.2.2

**Comment by Andireas1803** [comment]
It works, when I added `rotate by 0 degrees` at the end of the line. ;)

**Comment by Sharpjaws** [comment]
Thanks for the issue report. Although I was already aware of this bug. It's fixed in next release.
