### ISSUE TITLE
Cannot spawn a MythicMob

### ISSUE THREAD

**Issue by whoshenry** [Sharpjaws/SharpSK#31]
I can't get the right syntax for spawning a mythic mob.

The mob I have is called Horseman and that is the string too for MythicMobs.

I am doing this:
spawn a mythicmob "Horseman" at player

and it is saying it cannot understand it, I am using SharpSK-1.6.3

**Comment by abandonedaccount6235** [comment]
```
spawn [a] mythicmob %string% at %location% with level %integer%
```
is the syntax

**Comment by whoshenry** [comment]
Apologies, I literally just saw you have to add in the with level part.
