### ISSUE TITLE
Town of player returning none

### ISSUE THREAD

**Issue by nathan-li-dev** [Sharpjaws/SharpSK#35]
```
 command /townof:
  trigger:
    set {_t} to town of player
    broadcast "%{_t}%"
```
The above seems not to work, and always returns \<none\>, with SharpSK version 1.6.3, Towny 0.91.4.13, and Skript 2.2-dev30b bensku. Hook is set to true in config, and some other Towny expressions still work (tested mayor of "town").

**Comment by Eryk1983S** [comment]
It's not fixed at all.
Here my example:
command /banoftown <offline player>:
	 trigger:
		  set {_t} to town of player
		  set {_s} to town of sender
		  broadcast "%{_t}%, %{_s}%"

After using of this command there appears:
<none>, <none>

**Game-Version:** 1.12.2.
**Skript:** 2.2-dev37c
**SharpSK:** 1.6.3.
