### ISSUE TITLE
Authme Conditions

### ISSUE THREAD

**Issue by Feerko** [Sharpjaws/SharpSK#4]
Hello,
can you add to your addon something like this?

if player is registered:
if player is logged:

I'm really depend on this. I think it will be useful to many people.
Thanks! :)

**Comment by Feerko** [comment]
Hello, could you do that? I really need it. Thanks

**Comment by Snow-Pyon** [comment]
There is a player is registered condition already

**Comment by Sharpjaws** [comment]
Sorry for the respond delay, but as @Snow-Pyon said the first one has been included already and so is your second suggestion. However its my fault that I forgot to include it in the docs. Will do when I have the chance 

Use conditions:

```
%player% is [not] registerd //Checks if a player is registerd
%player% is [not] authenticated   //Checks if a player is logged in

```
