### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by Wqrld** [Sharpjaws/SharpSK#40]
```
            sharpsk save p1 (player's worldedit point 1) p2 (player's worldedit point 2) with origin (player's worldedit point 1) to clipboard of player
            sharpsk save clipboard of player to schematic "%arg 1%map"
            set {loc.%arg 1%.map} to player's worldedit point 1
         
        if "%arg 2%" contains "pasteschematic":
            sharpsk paste schematic "/home/pixel/ferox/plugins/WorldEdit/schematics/%arg 1%map" at {loc.%arg 1%.map}
```
I save a build to a schematic but when i try to paste it, it basicly pastes 180 degrees the other way. I can't rotate it on paste so is there a way to like keep the direction when saving a schematic? / allow for a direction in "worldedit point 1"?

**Comment by Sharpjaws** [comment]
Hi there, it is possible to rotate a schematic with the paste syntax like this:
```
sharpsk paste schematic "/home/pixel/ferox/plugins/WorldEdit/schematics/%arg 1%map" at {loc.%arg 1%.map} rotate by %number% degrees
```
Just adjust %number% to the amount of degrees you want to rotate it to.

**Comment by Wqrld** [comment]
I can't do this as I have no way to check which way the schematic is rotated when copying it/ it differs per schematic.
